Fix displayName for ES6 class component
kossnocorp/react-guard pull request #5
Opened 2016-12-08 11:24 UTC by havenchyk

Here is a method how React understands component's name https://github.com/facebook/react/blob/b3c75d82b2c8862a461b34167bbef37a3eaa5c46/src/classic/element/ReactElementValidator.js#L68

I guess react-guard can use the same

2016-12-08 11:41 UTC, kossnocorp requested changes
Thank you! It makes sense, but tests are missing.

2016-12-08 11:41 UTC, kossnocorp commented on test/react-15/index.js
>      t.true(guardSpy.called)
It's worth to add more examples. These lines are responsible for `this.constructor.displayName` test, but there is no tests for `this.constructor.name`

2016-12-08 12:17 UTC, havenchyk commented
Added some tests. Since property `name` of the constructor is read only, I just did `displayName` empty.

2016-12-10 12:24 UTC, havenchyk commented
@kossnocorp just a friendly ping :)

2016-12-12 08:10 UTC, kossnocorp approved these changes

2016-12-12 08:10 UTC, merged

2016-12-12 10:36 UTC, kossnocorp commented
Thank you! The update was released as `0.4.0`:

```
$ npm publish
+ react-guard@0.4.0
```

2016-12-12 10:41 UTC, havenchyk commented
awesome!